{
 "title": "SUSE CaaS Platform Certs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Errors Total",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(cert_exporter_error_total)" }
   ]
  },
  {
   "title": "Errors [1h]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cert_exporter_error_total[1h])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Kubernetes and ETCD PKI Certs Expiry",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "cert_exporter_cert_expires_in_seconds"
    }
   ]
  },
  {
   "title": "Kubeconfig Cert Expiry",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "cert_exporter_kubeconfig_expires_in_seconds"
    }
   ]
  },
  {
   "title": "Addon PKI Certs Expiry",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "cert_exporter_secret_expires_in_seconds"
    }
   ]
  }
 ]
}