{
 "title": "SUSE CaaS Platform Namespaces",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_labels,namespace)"
   },
   {
    "name": "pvc",
    "label": "PersistentVolumeClaim",
    "query": "label_values(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\"},persistentvolumeclaim)"
   },
   {
    "name": "masters",
    "label": "Masters",
    "query": "label_values(kube_node_spec_taint{effect=\"NoSchedule\",key=\"node-role.kubernetes.io/master\"}, node)"
   }
  ]
 },
 "panels": [
  { "title": "INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Working Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Workers Allocatable Mem",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node!~\"$masters\"})"
    }
   ]
  },
  {
   "title": "Working CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Workers Allocatable CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node!~\"$masters\"})"
    }
   ]
  },
  {
   "title": "Pods Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(kube_pod_container_info{namespace!=\"\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Workers Allocatable pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods{node!~\"$masters\"})"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_container_info{namespace=\"$namespace\"}) by (container_name)"
    }
   ]
  },
  {
   "title": "Images",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(kube_pod_container_info{namespace=\"$namespace\"}) by (image_id))"
    }
   ]
  },
  {
   "title": "CPU Cores Usage / Workers Allocatable CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(irate(container_cpu_usage_seconds_total{namespace!=\"\"}[5m])) / sum(kube_node_status_allocatable_cpu_cores{node!~\"$masters\"})) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage / Workers Allocatable Mem",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\"}) / sum(kube_node_status_allocatable_memory_bytes{node!~\"$masters\"}) * 100"
    }
   ]
  },
  {
   "title": "Pods Number / Workers Allocatable Pods",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=\"$namespace\"}) / sum(kube_node_status_allocatable_pods{node!~\"$masters\"}) * 100"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info{namespace=\"$namespace\"}) by (persistentvolume)"
    }
   ]
  },
  {
   "title": "VolumeClaims",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(kube_persistentvolumeclaim_info{namespace=\"$namespace\"}) by (persistentvolumeclaim))"
    }
   ]
  },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_service_info{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Workloads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_daemonset_labels{namespace=\"$namespace\"})",
     "legendFormat": "DaemonSets"
    },
    {
     "expr": "count(kube_deployment_labels{namespace=\"$namespace\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "count(kube_replicaset_status_fully_labeled_replicas{namespace=\"$namespace\"})",
     "legendFormat": "ReplicaSets"
    },
    {
     "expr": "count(kube_replicationcontroller_status_fully_labeled_replicas{namespace=\"$namespace\"})",
     "legendFormat": "ReplicationControllers"
    },
    {
     "expr": "count(kube_statefulset_labels{namespace=\"$namespace\"})",
     "legendFormat": "StatefulSets"
    }
   ]
  },
  {
   "title": "Pods Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Failed\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Pending\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Succeeded\"})",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Unknown\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "ConfigMaps",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_configmap_info{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Secrets",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_secret_info{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "WORKLOADS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workloads",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(kube_pod_owner{namespace=\"$namespace\", owner_kind!=\"<none>\"}) by (owner_name, owner_kind)"
      }
     ]
    }
   ]
  },
  {
   "title": "PODS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_info{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_info{namespace=\"$namespace\"}) by (pod, container, image)"
      }
     ]
    }
   ]
  },
  {
   "title": "VOLUMES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volumes",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "count(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\"}) by (namespace, persistentvolumeclaim)"
      },
      {
       "expr": "count(kube_persistentvolumeclaim_info{namespace=\"$namespace\", persistentvolumeclaim=~\"$pvc\"}) by (namespace, persistentvolumeclaim, volumename, storageclass)"
      },
      {
       "expr": "sum(kube_pod_spec_volumes_persistentvolumeclaims_readonly{namespace=\"$namespace\"}) by (namespace, persistentvolumeclaim)"
      },
      {
       "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"$pvc\"}) by (namespace, persistentvolumeclaim)"
      }
     ]
    }
   ]
  },
  {
   "title": "PODS MEMORY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Working Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container_name!=\"POD\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PODS CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container_name!=\"POD\"}[5m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PODS DISK I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOPS Read",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_reads_total{namespace=\"$namespace\", device=~\"(/dev/(sd|vd).*)\"}[5m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Throughput Read",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_reads_bytes_total{namespace=\"$namespace\"}[5m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "IOPS Read Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(container_fs_read_seconds_total{namespace=\"$namespace\", device=~\"(/dev/(sd|vd).*)\"} / container_fs_reads_total{namespace=\"$namespace\", device=~\"(/dev/(sd|vd).*)\"}) by (device, pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "IOPS Write",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_writes_total{namespace=\"$namespace\", device=~\"(/dev/(sd|vd).*)\"}[5m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Throughput Write",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_writes_bytes_total{namespace=\"$namespace\"}[5m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "IOPS Write Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(container_fs_write_seconds_total{namespace=\"$namespace\", device=~\"(/dev/(sd|vd).*)\"} / container_fs_writes_total{namespace=\"$namespace\", device=~\"(/dev/(sd|vd).*)\"}) by (device, pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PODS NETWORK",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Transmit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    }
   ]
  }
 ]
}